runtime: nodejs14
instance_class: F2

handlers:
  - url: /static
    static_dir: build/static
  - url: /(.*\.(js|css|json|ico|jpg|png|jpeg|gif|webp|html))$
    static_files: build/\1
    upload: build/(.*\.(js|css|json|ico|jpg|png|jpeg|gif|webp|html))$
  - url: .*
    script: auto
