steps:
  # Build and deploy the website to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['rsync', '-r', '-c', '-d', 'public/', 'gs://nftwebsite']

 
    #this next command is supposed to implement the cloudbuild if nothing else works
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp',  '-r', 'build/*', 'gs://nftwebsite']

 #these next set of codes are meant to install the npm build
  - name: 'node:16'
    entrypoint: 'npm'
    args: ['install']

  - name: 'node:16'
    entrypoint: 'npm'
    args: ['run', 'build']

# Optional: This section can be used for additional steps such as invalidating CDN caches, etc.
# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['app', 'deploy', 'app.yaml']

# Timeout for the entire build process
timeout: '1600s'  # Adjust as needed
