steps:
  # Build and deploy the website to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['rsync', '-r', '-c', '-d', 'public/', 'gs://nftwebsite']

  # Optional: Set appropriate ACLs for files in the bucket (public read)
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['acl', 'ch', '-r', 'public-read', 'gs://nftwebsite']

# Optional: This section can be used for additional steps such as invalidating CDN caches, etc.
# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['app', 'deploy', 'app.yaml']

# Timeout for the entire build process
timeout: '1600s'  # Adjust as needed
